# Generated by Django 4.2.5 on 2024-01-20 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_alter_doctor_hospital_alter_hospital_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='doctors.subject'),
        ),
    ]
